export const BANNER_STATUSES = ['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED', 'ARCHIVED'] as const;

export const PROMOTION_TYPES = ['PROMOTION', 'FLASH_DEAL'] as const;

export const PROMOTION_STATUSES = ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVE', 'EXPIRED', 'CANCELLED'] as const;

export const CONTENT_PAGE_STATUSES = ['DRAFT', 'PUBLISHED'] as const;

export const NOTIFICATION_BROADCAST_STATUSES = ['DRAFT', 'SENDING', 'SENT', 'FAILED'] as const;

export const NOTIFICATION_SEGMENTS = [
  'ALL_BUYERS',
  'ALL_SELLERS',
  'ALL_USERS',
] as const;

export const CONTENT_PAGE_SLUGS = ['faq', 'terms', 'privacy', 'help', 'about', 'contact'] as const;

export const SYSTEM_SETTING_KEYS = {
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  ENABLE_FLASH_DEALS: 'ENABLE_FLASH_DEALS',
  ENABLE_SELLER_PROMOTIONS: 'ENABLE_SELLER_PROMOTIONS',
  ENABLE_REVIEWS: 'ENABLE_REVIEWS',
  ENABLE_MESSAGING: 'ENABLE_MESSAGING',
  MAX_BANNER_COUNT: 'MAX_BANNER_COUNT',
  DEFAULT_DELIVERY_FEE_CDF: 'DEFAULT_DELIVERY_FEE_CDF',
  PLATFORM_ANNOUNCEMENT: 'PLATFORM_ANNOUNCEMENT',
} as const;

export const REPORT_TYPES = ['sales', 'financial', 'seller_performance'] as const;

export const MAX_BANNER_TITLE_LENGTH = 100;
export const MAX_BANNER_SUBTITLE_LENGTH = 200;
export const MAX_PROMOTION_TITLE_LENGTH = 150;
export const MAX_PROMOTION_DESCRIPTION_LENGTH = 500;
export const MAX_CONTENT_PAGE_SLUG_LENGTH = 50;
export const MAX_BROADCAST_MESSAGE_LENGTH = 160;
export const MAX_BROADCAST_TITLE_LENGTH = 100;
