/**
 * Server-side content validation for seller official documents (PR 2, D8).
 *
 * The client-asserted MIME type is never trusted: the accepted kind is read
 * from the file's magic bytes, and the declared type must AGREE with it (a
 * PDF renamed `.jpg`, or an executable labelled `image/png`, is refused).
 * Only PDF, JPEG and PNG are accepted — archives, executables, SVG (scriptable)
 * and every other format are rejected before anything reaches Cloudinary.
 *
 * Images are also stripped of embedded metadata (EXIF / XMP / IPTC / text
 * chunks) BEFORE upload, because Cloudinary keeps the metadata of the stored
 * original even with an incoming transformation (probed 2026-09-05): a phone
 * photo of an ID card would otherwise carry GPS coordinates into storage.
 * No native dependency: the JPEG and PNG containers are walked directly.
 */

export type DocumentKind = 'pdf' | 'jpeg' | 'png' | 'webp';

export interface SniffedDocument {
  kind: DocumentKind;
  mimeType: 'application/pdf' | 'image/jpeg' | 'image/png' | 'image/webp';
  /** Cloudinary resource_type that stores this kind privately. */
  resourceType: 'image' | 'raw';
  /** Extension used for the generated public_id / download name. */
  extension: 'pdf' | 'jpg' | 'png' | 'webp';
}

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/** MIME types a client may declare, and the kind each one must sniff as. */
const DECLARED_MIME_TO_KIND: Record<string, DocumentKind> = {
  'application/pdf': 'pdf',
  'image/jpeg': 'jpeg',
  'image/jpg': 'jpeg',
  'image/png': 'png',
  // WebP is what both seller clients produce for the legacy application
  // photo (client-side compression); NOT accepted as verification evidence.
  'image/webp': 'webp',
};

export const ACCEPTED_DOCUMENT_MIME_TYPES = Object.keys(DECLARED_MIME_TO_KIND);

/** Identify the container from its first bytes; null when unsupported. */
export function sniffDocument(buffer: Buffer): SniffedDocument | null {
  if (buffer.length < 8) return null;
  if (buffer.subarray(0, 5).toString('latin1') === '%PDF-') {
    return { kind: 'pdf', mimeType: 'application/pdf', resourceType: 'raw', extension: 'pdf' };
  }
  if (buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) {
    return { kind: 'jpeg', mimeType: 'image/jpeg', resourceType: 'image', extension: 'jpg' };
  }
  if (buffer.subarray(0, 8).equals(PNG_SIGNATURE)) {
    return { kind: 'png', mimeType: 'image/png', resourceType: 'image', extension: 'png' };
  }
  if (
    buffer.length >= 12 &&
    buffer.subarray(0, 4).toString('latin1') === 'RIFF' &&
    buffer.subarray(8, 12).toString('latin1') === 'WEBP'
  ) {
    return { kind: 'webp', mimeType: 'image/webp', resourceType: 'image', extension: 'webp' };
  }
  return null;
}

/**
 * The declared MIME type (multipart part header) must match the sniffed
 * kind. An unknown declared type is rejected even when the bytes look fine —
 * the client is lying about something.
 */
export function declaredTypeMatches(declared: string | undefined, sniffed: SniffedDocument): boolean {
  const normalized = (declared ?? '').split(';')[0].trim().toLowerCase();
  const expected = DECLARED_MIME_TO_KIND[normalized];
  return expected !== undefined && expected === sniffed.kind;
}

/**
 * Keep a human-readable but harmless name: strip paths, control characters
 * and anything outside [A-Za-z0-9._-], collapse runs, cap the length. Never
 * used to address storage — the public_id is generated by the API.
 */
export function sanitizeFilename(original: string | undefined, maxLength = 120): string | null {
  if (!original) return null;
  const base = original.split(/[\\/]/).pop() ?? '';
  const cleaned = base
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^A-Za-z0-9._-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^[._-]+/, '');
  if (!cleaned) return null;
  return cleaned.length > maxLength ? cleaned.slice(0, maxLength) : cleaned;
}

/**
 * Remove embedded metadata from an image buffer. JPEG: drops APP1 (EXIF/XMP),
 * APP2–APP13 (ICC, IPTC, Photoshop…) and COM segments, keeping APP0 (JFIF)
 * and APP14 (Adobe colour transform — needed to decode some CMYK files).
 * PNG: drops eXIf, tEXt, zTXt and iTXt chunks. PDFs are returned untouched
 * (they are stored as opaque raw files). Returns the original buffer when
 * the container is not recognised, so callers never lose the bytes.
 */
export function stripImageMetadata(buffer: Buffer, kind: DocumentKind): Buffer {
  if (kind === 'jpeg') return stripJpeg(buffer);
  if (kind === 'png') return stripPng(buffer);
  if (kind === 'webp') return stripWebp(buffer);
  return buffer;
}

function stripJpeg(buf: Buffer): Buffer {
  if (!(buf[0] === 0xff && buf[1] === 0xd8)) return buf;
  const out: Buffer[] = [buf.subarray(0, 2)];
  let i = 2;
  while (i + 4 <= buf.length) {
    if (buf[i] !== 0xff) break; // not a marker — bail out, keep the rest verbatim
    const marker = buf[i + 1];
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd7) || marker === 0x01) {
      out.push(buf.subarray(i, i + 2));
      i += 2;
      continue;
    }
    if (marker === 0xda) {
      // Start of scan: entropy-coded data follows until EOI — copy verbatim.
      out.push(buf.subarray(i));
      return Buffer.concat(out);
    }
    const len = buf.readUInt16BE(i + 2);
    const segment = buf.subarray(i, i + 2 + len);
    const isApp = marker >= 0xe0 && marker <= 0xef;
    const keep =
      !isApp && marker !== 0xfe /* COM */
        ? true
        : marker === 0xe0 /* APP0 JFIF */ || marker === 0xee /* APP14 Adobe */;
    if (keep) out.push(segment);
    i += 2 + len;
  }
  out.push(buf.subarray(i));
  return Buffer.concat(out);
}

const PNG_DROP = new Set(['eXIf', 'tEXt', 'zTXt', 'iTXt']);

function stripPng(buf: Buffer): Buffer {
  if (!buf.subarray(0, 8).equals(PNG_SIGNATURE)) return buf;
  const out: Buffer[] = [buf.subarray(0, 8)];
  let i = 8;
  while (i + 12 <= buf.length) {
    const len = buf.readUInt32BE(i);
    const type = buf.subarray(i + 4, i + 8).toString('latin1');
    const end = i + 12 + len;
    if (end > buf.length) break;
    if (!PNG_DROP.has(type)) out.push(buf.subarray(i, end));
    i = end;
    if (type === 'IEND') break;
  }
  if (i < buf.length) out.push(buf.subarray(i));
  return Buffer.concat(out);
}

const WEBP_DROP = new Set(['EXIF', 'XMP ']);

/** RIFF container: drop the EXIF and XMP chunks, fix the RIFF size field. */
function stripWebp(buf: Buffer): Buffer {
  if (buf.length < 12 || buf.subarray(8, 12).toString('latin1') !== 'WEBP') return buf;
  const chunks: Buffer[] = [];
  let i = 12;
  while (i + 8 <= buf.length) {
    const type = buf.subarray(i, i + 4).toString('latin1');
    const len = buf.readUInt32LE(i + 4);
    const padded = len + (len % 2);
    const end = Math.min(i + 8 + padded, buf.length);
    if (!WEBP_DROP.has(type)) chunks.push(buf.subarray(i, end));
    i = end;
  }
  const body = Buffer.concat(chunks);
  const header = Buffer.from(buf.subarray(0, 12));
  header.writeUInt32LE(4 + body.length, 4);
  return Buffer.concat([header, body]);
}
